---
stack: vngu/diana
version: '0.0.1'
description: diana
services:
  bot:
    image: pingu/telegram-diana:latest
    affinity:
      - node==grapefruit
    links:
      - system/lb
    instances: 1
    secrets:
      - secret: DIANA_BOT_TOKEN
        name: DIANA_BOT_TOKEN
        type: env
